var expt2_config = {
    nImages: 454,              // Total number of images available
    radius: 250,
    fixationDuration: 500,
    fixationPostTrial: 500,
    arrayPostTrial: 0,
    nStimuli: [2, 6],
    timePerItem: [250, 500],
    probePresent: [true, false],
    nTrialReps: 1,
    responseOptions: [
        "Yes - Sure",
        "Yes - Think",
        "Yes - Guess",
        "No - Guess", 
        "No - Think",
        "No - Sure",
    ],
    metaCapacity: false,
    metaOptions: ["number", "letter", "delay"],
    metaLetters: ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"],
    metaDuration: 5000,
    feedback: false,
    showFeedbackOptions: [false, true],
    feedbackDuration: 1500,
}